const state = { pesquisa:null, eventos:[], automaticScenarios:[], savedScenarios:[], charts:{} };
function setStatus(message,type='info'){const box=document.getElementById('statusBox');box.textContent=message;box.className=`status ${type}`;}
function safeNumber(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function pct(v,d=2){return `${safeNumber(v).toFixed(d).replace('.',',')}%`;}
function compact(t,max=72){if(!t)return'';return t.length>max?`${t.slice(0,max-1)}…`:t;}
async function loadPesquisa(){const {data,error}=await supabaseClient.from('pesquisas').select('id,codigo,titulo,status').eq('codigo',PESQUISA_CODIGO).single();if(error)throw new Error(`Erro ao carregar pesquisa: ${error.message}`);state.pesquisa=data;}
async function loadEventos(){const {data,error}=await supabaseClient.from('eventos_probabilidades_cenarios').select('*').eq('pesquisa_id',state.pesquisa.id).eq('ativo',true).order('ordem',{ascending:true});if(error)throw new Error(`Erro ao carregar eventos: ${error.message}`);state.eventos=data||[];}
async function loadSavedScenarios(){const {data,error}=await supabaseClient.from('cenarios_salvos').select('*').eq('pesquisa_id',state.pesquisa.id).order('criado_em',{ascending:true});if(error)throw new Error(`Erro ao carregar cenários salvos: ${error.message}`);state.savedScenarios=data||[];}
function scenarioProbability(combination){let probability=1;state.eventos.forEach(evento=>{const sv=combination[String(evento.numero)]||'indiferente';const p=safeNumber(evento.probabilidade_base,50)/100;if(sv==='ocorre')probability*=p;else if(sv==='nao_ocorre')probability*=(1-p);});return probability*100;}
function generateAutomaticScenarios(){const n=state.eventos.length,total=Math.pow(2,n),scenarios=[];for(let mask=0;mask<total;mask++){const combination={};state.eventos.forEach((evento,index)=>{combination[String(evento.numero)]=Boolean(mask&(1<<index))?'ocorre':'nao_ocorre';});scenarios.push({id:`cenario-${mask+1}`,nome:`Cenário ${mask+1}`,combinacao:combination,probabilidade:scenarioProbability(combination)});}state.automaticScenarios=scenarios.sort((a,b)=>b.probabilidade-a.probabilidade);}
function renderMetrics(){document.getElementById('metricEventos').textContent=state.eventos.length;document.getElementById('metricCenarios').textContent=state.automaticScenarios.length;const top=state.automaticScenarios[0];document.getElementById('metricTopScenario').textContent=top?pct(top.probabilidade,2):'-';document.getElementById('metricTopScenarioText').textContent=top?`${top.nome}: combinação automática com maior probabilidade estimada.`:'Aguardando cálculo dos cenários.';}
function renderEventsTable(){const tbody=document.getElementById('eventsTableBody');tbody.innerHTML='';state.eventos.forEach(evento=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${evento.numero}</td><td><strong>${evento.titulo}</strong><br><small>${evento.hipotese||''}</small></td><td>${pct(evento.probabilidade_base,1)}</td><td>${safeNumber(evento.importancia_media).toFixed(1).replace('.',',')}</td><td>${evento.origem_probabilidade}</td>`;tbody.appendChild(tr);});}
function stateBadge(value){if(value==='ocorre')return `<td><span class="badge badge-yes">Ocorre</span></td>`;if(value==='nao_ocorre')return `<td><span class="badge badge-no">Não ocorre</span></td>`;return `<td><span class="badge badge-any">Indiferente</span></td>`;}
function labelState(value){if(value==='ocorre')return'ocorre';if(value==='nao_ocorre')return'não ocorre';return'indiferente';}
function renderAutomaticTable(){const head=document.getElementById('autoTableHead'),body=document.getElementById('autoTableBody'),topRows=state.automaticScenarios.slice(0,12);head.innerHTML=`<tr><th>Cenário</th><th>Probabilidade</th>${state.eventos.map(e=>`<th>E${e.numero}</th>`).join('')}</tr>`;body.innerHTML='';topRows.forEach((scenario,index)=>{const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${index+1}. ${scenario.nome}</strong></td><td><strong>${pct(scenario.probabilidade,3)}</strong></td>${state.eventos.map(e=>stateBadge(scenario.combinacao[String(e.numero)])).join('')}`;body.appendChild(tr);});}
function destroyChart(id){if(state.charts[id]){state.charts[id].destroy();delete state.charts[id];}}
function renderCharts(){renderRankingChart();renderFrequencyChart();}
function renderRankingChart(){destroyChart('rankingChart');const rows=state.automaticScenarios.slice(0,10),ctx=document.getElementById('rankingChart');state.charts.rankingChart=new Chart(ctx,{type:'bar',data:{labels:rows.map((r,i)=>`C${i+1}`),datasets:[{label:'Probabilidade do cenário (%)',data:rows.map(r=>Number(r.probabilidade.toFixed(4))),backgroundColor:rows.map((_,i)=>['rgba(40,79,125,.76)','rgba(36,112,109,.72)','rgba(194,138,44,.72)','rgba(101,112,105,.62)'][i%4]),borderColor:'rgba(23,32,24,.18)',borderWidth:1}]},options:{responsive:true,plugins:{tooltip:{callbacks:{afterLabel:(ctx)=>{const s=rows[ctx.dataIndex];return state.eventos.map(e=>`E${e.numero}: ${labelState(s.combinacao[String(e.numero)])}`);}}}},scales:{y:{beginAtZero:true,title:{display:true,text:'Probabilidade (%)'}}}}});}
function renderFrequencyChart(){destroyChart('frequencyChart');const topRows=state.automaticScenarios.slice(0,12),ctx=document.getElementById('frequencyChart');const counts=state.eventos.map(evento=>topRows.filter(s=>s.combinacao[String(evento.numero)]==='ocorre').length);state.charts.frequencyChart=new Chart(ctx,{type:'doughnut',data:{labels:state.eventos.map(e=>`E${e.numero}`),datasets:[{label:'Ocorrências nos cenários prioritários',data:counts,backgroundColor:['rgba(40,79,125,.80)','rgba(36,112,109,.78)','rgba(194,138,44,.78)','rgba(154,61,54,.70)','rgba(82,95,135,.72)','rgba(45,122,76,.72)'],borderColor:'#fffdf8',borderWidth:2}]},options:{responsive:true,plugins:{tooltip:{callbacks:{afterLabel:(ctx)=>compact(state.eventos[ctx.dataIndex].titulo,90)}}}}});}
function radioOption(numero,value,label,selected){const id=`manual_${numero}_${value}`;return `<label><input type="radio" name="evento_${numero}" id="${id}" value="${value}" ${selected===value?'checked':''}><span>${label}</span></label>`;}
function renderManualControls(){const grid=document.getElementById('manualControls');grid.innerHTML='';const def={'1':'ocorre','2':'nao_ocorre','3':'ocorre','4':'nao_ocorre','5':'nao_ocorre','6':'ocorre'};state.eventos.forEach(evento=>{const value=def[String(evento.numero)]||'indiferente';const article=document.createElement('article');article.className='manual-card';article.innerHTML=`<strong>E${evento.numero} — ${evento.titulo}</strong><div class="segmented">${radioOption(evento.numero,'ocorre','Ocorre',value)}${radioOption(evento.numero,'nao_ocorre','Não ocorre',value)}${radioOption(evento.numero,'indiferente','Indiferente',value)}</div>`;grid.appendChild(article);});calculateManualScenario();}
function getManualCombination(){const combination={};state.eventos.forEach(evento=>{const checked=document.querySelector(`input[name="evento_${evento.numero}"]:checked`);combination[String(evento.numero)]=checked?checked.value:'indiferente';});return combination;}
function calculateManualScenario(){const combination=getManualCombination(),probability=scenarioProbability(combination);document.getElementById('manualProbability').textContent=pct(probability,4);const occurs=Object.values(combination).filter(v=>v==='ocorre').length,notOccurs=Object.values(combination).filter(v=>v==='nao_ocorre').length;document.getElementById('manualInterpretation').textContent=`Este cenário combina ${occurs} evento(s) ocorrendo e ${notOccurs} evento(s) não ocorrendo. Eventos marcados como “indiferente” não alteram o cálculo.`;}
async function saveManualScenario(){const combination=getManualCombination(),probability=scenarioProbability(combination),nome=document.getElementById('manualScenarioName').value.trim()||'Cenário simulado pelo usuário',descricao=document.getElementById('manualScenarioDescription').value.trim()||null;const payload={pesquisa_id:state.pesquisa.id,nome,descricao,combinacao_json:combination,probabilidade_calculada:Number(probability.toFixed(6)),observacao:'Cenário salvo pela interface de Geração e Cruzamento de Cenários.',atualizado_em:new Date().toISOString()};const {error}=await supabaseClient.from('cenarios_salvos').upsert(payload,{onConflict:'pesquisa_id,nome'});if(error)throw new Error(`Erro ao salvar cenário: ${error.message}`);await loadSavedScenarios();renderSavedScenarios();setStatus('Cenário manual salvo no Supabase.','success');}
function badgeClass(value){if(value==='ocorre')return'badge-yes';if(value==='nao_ocorre')return'badge-no';return'badge-any';}
function renderSavedScenarios(){const grid=document.getElementById('savedScenarios');grid.innerHTML='';if(!state.savedScenarios.length){grid.innerHTML='<article class="saved-card"><p>Nenhum cenário salvo.</p></article>';return;}state.savedScenarios.forEach(cenario=>{const combination=cenario.combinacao_json||{},probability=scenarioProbability(combination),card=document.createElement('article');card.className='saved-card';card.innerHTML=`<h3>${cenario.nome}</h3><p>${cenario.descricao||''}</p><p><strong>Probabilidade estimada:</strong> ${pct(probability,4)}</p><div class="combination-list">${state.eventos.map(e=>`<span class="badge ${badgeClass(combination[String(e.numero)])}">E${e.numero}: ${labelState(combination[String(e.numero)])}</span>`).join('')}</div><div class="saved-actions"><button type="button" class="ghost-btn" data-action="load" data-id="${cenario.id}">Carregar no simulador</button></div>`;grid.appendChild(card);});}
function loadSavedIntoManual(id){const scenario=state.savedScenarios.find(s=>s.id===id);if(!scenario)return;const combination=scenario.combinacao_json||{};state.eventos.forEach(evento=>{const value=combination[String(evento.numero)]||'indiferente';const radio=document.querySelector(`input[name="evento_${evento.numero}"][value="${value}"]`);if(radio)radio.checked=true;});document.getElementById('manualScenarioName').value=scenario.nome;document.getElementById('manualScenarioDescription').value=scenario.descricao||'';calculateManualScenario();window.scrollTo({top:document.querySelector('#manualControls').offsetTop-120,behavior:'smooth'});}
function downloadText(filename,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
function exportJson(){downloadText('cenarios_md2036.json',JSON.stringify({pesquisa:state.pesquisa,eventos:state.eventos,cenarios_automaticos:state.automaticScenarios,cenarios_salvos:state.savedScenarios},null,2),'application/json');}
function exportCsv(){const rows=state.automaticScenarios.slice(0,64),header=['ranking','cenario','probabilidade',...state.eventos.map(e=>`E${e.numero}`)],lines=[header.join(';')];rows.forEach((scenario,index)=>{lines.push([index+1,scenario.nome,scenario.probabilidade.toFixed(6).replace('.',','),...state.eventos.map(e=>labelState(scenario.combinacao[String(e.numero)]))].join(';'));});downloadText('cenarios_md2036.csv',lines.join('\n'),'text/csv;charset=utf-8');}
async function loadAll(){setStatus('Carregando dados...','info');await loadPesquisa();await loadEventos();await loadSavedScenarios();generateAutomaticScenarios();renderMetrics();renderEventsTable();renderAutomaticTable();renderCharts();renderManualControls();renderSavedScenarios();setStatus('Dados carregados. A página já contém exemplos pré-preenchidos para o storytelling.','success');}
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('reloadBtn').addEventListener('click',()=>loadAll().catch(err=>setStatus(err.message,'error')));document.getElementById('calcManualBtn').addEventListener('click',calculateManualScenario);document.getElementById('saveManualBtn').addEventListener('click',()=>saveManualScenario().catch(err=>setStatus(err.message,'error')));document.getElementById('manualControls').addEventListener('change',calculateManualScenario);document.getElementById('exportJsonBtn').addEventListener('click',exportJson);document.getElementById('exportCsvBtn').addEventListener('click',exportCsv);document.getElementById('savedScenarios').addEventListener('click',event=>{const btn=event.target.closest("button[data-action='load']");if(btn)loadSavedIntoManual(btn.dataset.id);});loadAll().catch(err=>{console.error(err);setStatus(err.message,'error');});});
